export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as RegisterSeat} from './RegisterSeat'
export {default as SortSeat} from './SortSeat'